### PR TITLE
styling updated fixes #33 

### LINKED ISSUE #33: [Adding/Updating] Updating The header section as according to alignment and other requirements.
Header Section is not aligned neatly so updating it and styling it

Assigned me issue as label of hacktoberfest.

### PR DESCRIPTION
**Pull request by rajvinder-kaur**
updated the ui and balanced it with a neutral tone for better user experience. and commented out the extra code that was causing a replication of home page  fixes #33 #30
icc1
icc2
icc3

### CODE REVIEW

**Comment by NSmonish** [comment]
The website's colour theme is taken from this year's WC theme, which will remain unchanged, and the social media icons are too far apart.

**Comment by rajvinder-kaur** [comment]
please review these changes on ui palatte
icc4
icc5

**Review by varun10sudhir — COMMENTED** [review]
Hi @rajvinder-kaur !
You are using an older version of the repo, kindly sync the latest changes and then make your commits.
Thank you

**Comment by rajvinder-kaur** [comment]
i have updated my fork but still i am unable to solve the conflicts and the button is disabled.
image

**Pull request closed without merging**
