### PR TITLE
added fonts and fixed alignment

### PR DESCRIPTION
**Pull request by Shivangbhatnagar237**
### Description: 
This pull request introduces an enhancement to the Cricket World Cup 2023 website by updating the font choices with those obtained from the original website. I also fixed the alignment of the team info on the landing page with 
```align-items: center``` in ```styles.css``` The purpose of this change is to enhance the website's design and overall aesthetics, resulting in a more visually appealing and user-friendly experience for visitors.

fixes: #43 

- [x]  I have tested the changes locally to ensure they work as expected.
- [x] I have provided clear and concise descriptions for the changes made.

### Screenshots: 

<details>
  <summary>Landing page</summary>
  
  image
</details>

<details>
  <summary>Standings</summary>
  
  image
</details>

<details>
  <summary>Fixtures</summary>
  
  image
</details>

<details>
  <summary>Fan Polls</summary>
  
  image
</details>

Your feedback and suggestions regarding these font updates are greatly appreciated. Thank you for considering this enhancement.

### CODE REVIEW

**Comment by Shivangbhatnagar237** [comment]
cc @varun10sudhir

**Comment by Shivangbhatnagar237** [comment]
@varun10sudhir Okay, I understood the flag-alignment issue, but couldn't quite get the 'links underlined' thing. Can you please tell me more about that?

**Comment by varun10sudhir** [comment]
Hi @Shivangbhatnagar237 !
I am attaching the screenshot of the landing page according to your code

image


I can see the changes made to the font, however the links are still underlined and the table alignment is off.
Kindly look into this

Thank you

**Comment by Shivangbhatnagar237** [comment]
> Hi @Shivangbhatnagar237 !
> I am attaching the screenshot of the landing page according to your code
> 
> image
> 
> 
> I can see the changes made to the font, however the links are still underlined and the table alignment is off.
> Kindly look into this
> 
> Thank you
> 

Oh, okay I'll fix that, thanks

**Pull request closed without merging**
