### PR TITLE
Fix: ICC WC logo

### PR DESCRIPTION
**Pull request by Ronit-gurjar**
hey @NSmonish 

I have added the logo (ICC-WC-2023.png) and implemented necessary requirements to make it look proper🔥

### BEFORE :-
Screenshot_20231014_181321

### AFTER :-
Screenshot_20231014_181411

### CODE REVIEW

**Review by NSmonish — CHANGES_REQUESTED** [review]
Although the new ICC World Cup logo appears better, it has to be brighter to be seen clearly.

**Comment by Ronit-gurjar** [comment]
@NSmonish 

I have fixed the issue.
the issue was caused due to following block of code :-
image

> I found about this error after enhancing the old logo😂 now the logo looks x2 good.

`Suggestion` :- i would recommend changing the background-color from `#320073` to `#1D0042` for a better contrast, in body and header

**Comment by NSmonish** [comment]
> @NSmonish
> 
> I have fixed the issue. the issue was caused due to following block of code :- image
> 
> > I found about this error after enhancing the old logo😂 now the logo looks x2 good.
> 
> `Suggestion` :- i would recommend changing the background-color from `#320073` to `#1D0042` for a better contrast, in body and header

yes the opacity is the problem, change it to 1.0 and create a PR. The background colour is made according to the colour code of official icc wc 23.

**Comment by Ronit-gurjar** [comment]
@NSmonish  the above PR already contains the changes

**Comment by Ronit-gurjar** [comment]
> > @NSmonish
> > I have fixed the issue. the issue was caused due to following block of code :- image
> > > I found about this error after enhancing the old logo😂 now the logo looks x2 good.
> > 
> > 
> > `Suggestion` :- i would recommend changing the background-color from `#320073` to `#1D0042` for a better contrast, in body and header
> 
> yes the opacity is the problem, change it to 1.0 and create a PR. The background colour is made according to the colour code of official icc wc 23.

Changes Done

**Pull request merged**
